name: build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  Run_code_quality_tasks_and_linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Copy .env file
        run: cp .env.example .env
      - name: Install dependencies
        run: |
          composer install
      - name: Run PHPStan
        run: |
          vendor/bin/phpstan analyse --memory-limit=2G
      - name: Run Php cs fixer
        run: |
          vendor/bin/phpcs

  Php_vulnerability_scan:
    runs-on: ubuntu-latest
    needs: Run_code_quality_tasks_and_linters
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Copy .env file
        run: cp .env.example .env
      - name: Install dependencies
        run: |
          composer require roave/security-advisories:dev-latest
      - name: Run security scan
        run: |
          vendor/bin/roave/security-advisories check

  Nodejs_vulnerability_scan:
    runs-on: ubuntu-latest
    needs: Run_code_quality_tasks_and_linters
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run audit
        run: npm audit --audit-level=high

  Build_composer:
    runs-on: ubuntu-latest
    needs:
      - Run_code_quality_tasks_and_linters
      - Php_vulnerability_scan
      - Nodejs_vulnerability_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: |
          composer install
          composer dump-autoload -o
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: vendor/
          retention-days: 2

  Build_node:
    runs-on: ubuntu-latest
    needs:
      - Run_code_quality_tasks_and_linters
      - Php_vulnerability_scan
      - Nodejs_vulnerability_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: public-node-modules
          path: | 
            public/
            node_modules/
          retention-days: 2